"""Human-readable identity for a rules corpus version.

`rc_4905f02b8dfdd414` is exact but unreadable. Every version also gets a deterministic two-word name
(e.g. "steady-harbor") derived from its hash, so people can tell rule sets apart at a glance on
reviews and history. The name is presentation only; the version string stays the source of truth.
"""

import hashlib

from sar_plimsoll.rules.ingest import UNINITIALISED_CORPUS

_ADJECTIVES = (
    "amber",
    "azure",
    "bold",
    "brave",
    "bright",
    "brisk",
    "calm",
    "clear",
    "coastal",
    "cobalt",
    "copper",
    "coral",
    "crisp",
    "dawn",
    "deep",
    "dusk",
    "eastern",
    "ember",
    "fair",
    "fleet",
    "frosty",
    "gentle",
    "golden",
    "grey",
    "high",
    "iron",
    "jade",
    "keen",
    "level",
    "long",
    "lucky",
    "misty",
    "noble",
    "northern",
    "open",
    "pale",
    "proud",
    "quiet",
    "rapid",
    "royal",
    "salt",
    "sandy",
    "scarlet",
    "silver",
    "slate",
    "snowy",
    "southern",
    "steady",
    "still",
    "stout",
    "swift",
    "tall",
    "teal",
    "tidal",
    "true",
    "twin",
    "velvet",
    "vivid",
    "warm",
    "western",
    "white",
    "wild",
    "windy",
    "young",
)
_NOUNS = (
    "anchor",
    "bay",
    "beacon",
    "bearing",
    "breaker",
    "buoy",
    "cabin",
    "cape",
    "channel",
    "compass",
    "cove",
    "current",
    "deck",
    "dock",
    "estuary",
    "fathom",
    "ferry",
    "flag",
    "galley",
    "gull",
    "harbor",
    "haven",
    "headland",
    "helm",
    "horizon",
    "hull",
    "inlet",
    "isle",
    "jetty",
    "keel",
    "knot",
    "lagoon",
    "lantern",
    "lighthouse",
    "mainsail",
    "marina",
    "mast",
    "mooring",
    "narrows",
    "oar",
    "pier",
    "port",
    "quay",
    "reef",
    "rigging",
    "rudder",
    "sail",
    "schooner",
    "shoal",
    "sound",
    "spar",
    "starboard",
    "strait",
    "swell",
    "tide",
    "tiller",
    "voyage",
    "wake",
    "wharf",
    "windlass",
    "yard",
    "sextant",
    "lanyard",
    "bowline",
)


def rules_label(version: str | None) -> str:
    if not version or version == UNINITIALISED_CORPUS:
        return "no rules"
    digest = hashlib.sha256(version.encode()).digest()
    return f"{_ADJECTIVES[digest[0] % len(_ADJECTIVES)]}-{_NOUNS[digest[1] % len(_NOUNS)]}"


def short_version(version: str | None) -> str | None:
    if not version or version == UNINITIALISED_CORPUS:
        return None
    return version[:9]
